### ISSUE TITLE
使用pip安装hibiapi时无限创建configs

### ISSUE THREAD

**Issue by Orisland** [mixmoe/HibiAPI#113]
如题，安装hibiapi成功后启动api，
```python
[root@vultrguest configs]# hibiapi
Traceback (most recent call last):
  File "/usr/local/bin/hibiapi", line 5, in <module>
    from hibiapi.__main__ import main
  File "/usr/local/lib/python3.8/site-packages/hibiapi/__main__.py", line 10, in <module>
    from .utils.config import CONFIG_DIR, DEBUG, Config
  File "/usr/local/lib/python3.8/site-packages/hibiapi/utils/config.py", line 36, in <module>
    assert _generate_default() <= 0, "Please complete config file!"
  File "/usr/local/lib/python3.8/site-packages/hibiapi/utils/config.py", line 27, in _generate_default
    default_path.read_text(encoding="utf-8"),
  File "/usr/lib64/python3.8/pathlib.py", line 1235, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib64/python3.8/pathlib.py", line 1221, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
IsADirectoryError: [Errno 21] Is a directory: '/usr/local/lib/python3.8/site-packages/hibiapi/configs/configs'
```
且，每次输入hibiapi后似乎都会创建一个新的conifg，然后无限错误，疑似bug？
```python
[root@vultrguest configs]# ls
bilibili.yml  general.yml  pixiv.yml   sauce.yml
configs       netease.yml  qrcode.yml  tieba.yml
[root@vultrguest configs]# tree configs/
configs/
|-- configs
|   `-- general.yml
`-- general.yml

1 directory, 2 files
[root@vultrguest configs]# 
```

**Comment by Orisland** [comment]
> 好迷惑的bug…
> 试试给hibiapi单独找一个文件夹运行

直接单独克隆独立文件夹后问题解决，刚才出现问题的路径大概是这样的
`/hibiapi/Hibiapi/....`

**Comment by mnixry** [comment]
> 我进入hibiapi目录中使用命令`hibiapi`启动api时，一定会报上述错误，我必须退出该文件夹，回到hibiapi的根目录使用hibiapi指令才可以正常使用？似乎是我的问题？但是pip安装似乎一直都是这个问题，暂时没有确定到底是哪出的问题。

`hibiapi`会在当前工作目录寻找`configs`目录, 找不到就会创建并退出, 所以你需要在修改完配置文件后退回到母目录

<details>

<summary>相关代码</summary>

https://github.com/mixmoe/HibiAPI/blob/d997c5a2bf3cdbccc758d7036447e443c6b6f0ff/hibiapi/utils/config.py#L12-L30

</details>

**Comment by Orisland** [comment]
> > 我进入hibiapi目录中使用命令`hibiapi`启动api时，一定会报上述错误，我必须退出该文件夹，回到hibiapi的根目录使用hibiapi指令才可以正常使用？似乎是我的问题？但是pip安装似乎一直都是这个问题，暂时没有确定到底是哪出的问题。
> 
> `hibiapi`会在当前工作目录寻找`configs`目录, 找不到就会创建并退出, 所以你需要在修改完配置文件后退回到母目录
> 
> 相关代码
> https://github.com/mixmoe/HibiAPI/blob/d997c5a2bf3cdbccc758d7036447e443c6b6f0ff/hibiapi/utils/config.py#L12-L30

所以换句话说，我必须进入hibiapi根目录里才可以正常启动hibiapi。
