### ISSUE TITLE
按照Dockerfile文件制作容器后无法访问，链接被终止

### ISSUE THREAD

**Issue by yuukiyuuna** [mixmoe/HibiAPI#150]
你好，我是直接克隆该项目然后直接执行制作的镜像

docker容器启动命令：

```shell
docker run -d -p 0.0.0.0:8080:8080 hibiapi:lastet
```
客户端访问：
![image](https://user-images.githubusercontent.com/17798350/137083507-28dba2fb-2f28-4d01-9c94-25f3c0618fc0.png)

服务端日志信息：

<details>

```
2021-10-13 07:00:51.411 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:134 - Invalid HTTP request received.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 3
               │     └ 10
               └ <function _main at 0x7f936fb1fb80>
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 3
           │    └ <function BaseProcess._bootstrap at 0x7f936fcf61f0>
           └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f936fcf3820>
    └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7f936fd9dd30>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
    │    └ <function subprocess_started at 0x7f936ecddf70>
    └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8080)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x7f936fd9dcd0>>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8080)>]
           │       │   │    └ <function Server.serve at 0x7f936ecdd4c0>
           │       │   └ <uvicorn.server.Server object at 0x7f936fd9dcd0>
           │       └ <function run at 0x7f936fac6310>
           └ <module 'asyncio' from '/usr/local/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f936e14ddc0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 131, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xa2\xd21\xdd\xf5\\Ai\xc4\xa8\xc1\xf9\n\xc9\xfaN\xe5\xe3\xf3\x13\xa3\x13\x17\\\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7f936538ec70>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7f9364990ee0>
  File "httptools/parser/parser.pyx", line 212, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: Invalid method encountered
2021-10-13 07:00:51.419 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:134 - Invalid HTTP request received.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 3
               │     └ 10
               └ <function _main at 0x7f936fb1fb80>
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 3
           │    └ <function BaseProcess._bootstrap at 0x7f936fcf61f0>
           └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f936fcf3820>
    └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7f936fd9dd30>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
    │    └ <function subprocess_started at 0x7f936ecddf70>
    └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8080)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x7f936fd9dcd0>>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8080)>]
           │       │   │    └ <function Server.serve at 0x7f936ecdd4c0>
           │       │   └ <uvicorn.server.Server object at 0x7f936fd9dcd0>
           │       └ <function run at 0x7f936fac6310>
           └ <module 'asyncio' from '/usr/local/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f936e14ddc0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 107, in handler
    await handle_http(
          └ <function handle_http at 0x7f936ecdd040>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/_handlers/http.py", line 83, in handle_http
    protocol.data_received(data)
    │        │             └ bytearray(b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x8c\xf3M\x9d)\xa4\\|gY\xf3\xe8\xe1\xe1`\xc1u4\xffb\x84\xb5\xe5\xb5\x...
    │        └ <function HttpToolsProtocol.data_received at 0x7f936d0ee0d0>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7f9364990940>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 131, in data_received
    self.parser.feed_data(data)
    │    │      │         └ bytearray(b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x8c\xf3M\x9d)\xa4\\|gY\xf3\xe8\xe1\xe1`\xc1u4\xffb\x84\xb5\xe5\xb5\x...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7f936538eb80>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7f9364990940>
  File "httptools/parser/parser.pyx", line 212, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: Invalid method encountered
2021-10-13 07:00:51.490 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:134 - Invalid HTTP request received.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 3
               │     └ 10
               └ <function _main at 0x7f936fb1fb80>
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 3
           │    └ <function BaseProcess._bootstrap at 0x7f936fcf61f0>
           └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f936fcf3820>
    └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7f936fd9dd30>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
    │    └ <function subprocess_started at 0x7f936ecddf70>
    └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8080)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x7f936fd9dcd0>>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8080)>]
           │       │   │    └ <function Server.serve at 0x7f936ecdd4c0>
           │       │   └ <uvicorn.server.Server object at 0x7f936fd9dcd0>
           │       └ <function run at 0x7f936fac6310>
           └ <module 'asyncio' from '/usr/local/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f936e14ddc0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 131, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b"\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03&\xd4|\x8b\x80\x9d\xef\x9a\xc5\x9af\xf5:\xaf\xc2\xab\xd9e\xbdJ\xa7\xdd`c^M\xda\...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7f93649a2040>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7f93649a0340>
  File "httptools/parser/parser.pyx", line 212, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: Invalid method encountered
2021-10-13 07:00:51.747 | WARNING  | uvicorn.protocols.http.httptools_impl:data_received:134 - Invalid HTTP request received.
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 3
               │     └ 10
               └ <function _main at 0x7f936fb1fb80>
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 3
           │    └ <function BaseProcess._bootstrap at 0x7f936fcf61f0>
           └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f936fcf3820>
    └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7f936fd9dd30>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
    │    └ <function subprocess_started at 0x7f936ecddf70>
    └ <SpawnProcess name='SpawnProcess-1' parent=7 started>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8080)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x7f936fd9dcd0>>
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8080)>]
           │       │   │    └ <function Server.serve at 0x7f936ecdd4c0>
           │       │   └ <uvicorn.server.Server object at 0x7f936fd9dcd0>
           │       └ <function run at 0x7f936fac6310>
           └ <module 'asyncio' from '/usr/local/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f936e14ddc0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 131, in data_received
    self.parser.feed_data(data)
    │    │      │         └ b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xc63\x87Y\x9c\xafV\x1a\t\xa3\x11\x84\xc9\x0e\xd2k\x03\xd1\x9d\x89\x1bIw\x04\x1...
    │    │      └ <method 'feed_data' of 'httptools.parser.parser.HttpParser' objects>
    │    └ <httptools.parser.parser.HttpRequestParser object at 0x7f936538eb80>
    └ <uvicorn.protocols.http.httptools_impl.HttpToolsProtocol object at 0x7f9364990ca0>
  File "httptools/parser/parser.pyx", line 212, in httptools.parser.parser.HttpParser.feed_data

httptools.parser.errors.HttpParserInvalidMethodError: Invalid method encountered
```

</details>

请问是编译的时候有问题么

**Comment by yuukiyuuna** [comment]
你好，按照你的指导已经可以在本地访问了，状态码是200
![image](https://user-images.githubusercontent.com/17798350/137234604-44df661f-a450-42d4-86bc-ee5e59a5bd5c.png)


但是有一个比较奇怪的地方是，我通过外网访问网站显示响应时间过长，抓了一下包发现服务器没有回报
![image](https://user-images.githubusercontent.com/17798350/137234842-70185bc1-e560-42dd-9221-7149dfdd5876.png)
![image](https://user-images.githubusercontent.com/17798350/137234901-a4ae6ac9-91a9-4b65-8a46-d1d62782155e.png)


容器日志里也只有我本地访问的日志
![image](https://user-images.githubusercontent.com/17798350/137235113-09bd8e3b-c8b2-4db1-8e68-b0ed5be00cc6.png)

**Comment by yuukiyuuna** [comment]
你好，查了一下确实是云服务器的问题，目前已可以正常访问

想麻烦再问一下，我之前看看过其他issue，我手动进容器改过这个参数，可以在最开始的日志中看到过，但并没有生效
如果只能在启容器指定变量的方式更改的话，可更改的变量有哪些可以告诉我一下么
