### ISSUE TITLE
首次启动时遇到的错误

### ISSUE THREAD

**Issue by ObcbO** [mixmoe/HibiAPI#241]
我输入
```
git clone https://github.com/mixmoe/HibiAPI.git
cd HibiAPI
pip install .
python -m hibiapi
```
后，就出现以下报错
```
root@goorm:/workspace/python/HibiAPI(main)# python -m hibiapi
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/workspace/python/HibiAPI/hibiapi/__init__.py", line 13, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'
```

**Comment by mnixry** [comment]
请通过`pip --version`确保你使用的Python版本为`3.8`或者以上
